### ISSUE TITLE
Enhancing the 'Coverage' Command for Detailed Action/Permission Conditions

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#837]
### Description
We need to improve the accuracy and detail of the 'Coverage' command used in evaluating action/permission conditions within our system. A key concern is ensuring that every aspect of a permission condition is thoroughly covered and assessed for accuracy. The current implementation may lead to incomplete assessments, as exemplified by the sample condition provided.

### Sample Condition for Reference
```
permission view = system.view or ((is_public or (is_partner and partner) or (viewer or company.maintain or organization.maintain or team.view)) not denied)
```

In this example, asserting only a part of the condition (like `system.view`) is considered sufficient for coverage, even if other parts are not asserted. This approach can lead to suboptimal results and inaccuracies in permission evaluation.

### Suggested Improvements
- **Detail Each Component**: Ensure that each component of a permission condition (e.g., `is_public`, `is_partner`) is individually evaluated and asserted in the 'Coverage' command.
- **Comprehensive Coverage Analysis**: Modify the 'Coverage' command to analyze all aspects of a condition, preventing partial or incomplete evaluations.
- **Quality Checks**: Introduce quality checks to validate the comprehensiveness and accuracy of the coverage.

### Goals
- **Accurate Coverage Assessment**: Achieve a more accurate and thorough evaluation of permission conditions.

### Action Items
- [ ] Review the current implementation of the 'Coverage' command.
- [ ] Redesign the command to incorporate detailed assessments of each condition part.
- [ ] Implement tests and quality checks for the revised 'Coverage' command.
- [ ] Update documentation to reflect the new standards and procedures.

### Request for Comments
We seek feedback and suggestions, particularly regarding:
- Approaches for enhancing detail and accuracy in the 'Coverage' command.
- Potential challenges and solutions in the redesign process.
- Ideas to ensure the effectiveness of the new implementation.

**Comment by ayewo** [comment]
@tolgaOzen 

1. Can you point me to the “Coverage” command in the codebase?
2. In your example, I imagine that short-circuiting is happening because `system.view` is the highest access available but then you go on to say:
>  This approach can lead to suboptimal results and inaccuracies in permission evaluation.

Can you please clarify the inaccuracy?

**Comment by rishi-jat** [comment]
@tolgaozen Is this bounty still open to work? Thanks!

**Comment by matiasmagni** [comment]
/attempt #837

### **Objective**

Upgrade `permify coverage` to detect when specific parts of a permission rule (like the `B` in `A OR B`) are skipped during testing due to short-circuit logic.

### **The Plan**

1. **Update the AST (Abstract Syntax Tree)**
* Ensure every node in the schema parser (ANDs, ORs, attribute checks) includes **Source Position** (Line & Column number).
* Generate a unique ID for every node based on its position so we can track it.

2. **Build a Coverage Registry**
* Create a map that initializes every logic node in the schema with a `visit_count` of 0.
* This registry will serve as the scorecard for the test run.

3. **Instrument the Evaluator (The "Visitor")**
* Inject a listener into the runtime evaluation logic.
* **The Logic:** When the engine evaluates a condition, increment its `visit_count`.
* **The Fix:** Explicitly capture "short-circuits."
* If `A OR B` evaluates `A` as `true`, the engine stops. `B` remains at 0 visits.
* If `A AND B` evaluates `A` as `false`, the engine stops. `B` remains at 0 visits.

4. **Report the Gaps**
* After tests finish, query the registry.
* Any node with `visit_count == 0` is reported as "Missing Coverage" with its exact Line:Column location.

**Comment by matiasmagni** [comment]
/claim #837 @tolgaozen  PR: https://github.com/Permify/permify/pull/2743

**Comment by CuboYe** [comment]
/claim 837

Claiming territory for a scoped fix attempt now. If maintainer preference differs, I can adapt quickly.

**Comment by CuboYe** [comment]
/claim 837

Claiming territory for a scoped fix attempt now. If maintainer preference differs, I can adapt quickly.

**Comment by tribhuwan-kumar** [comment]
@tolgaozen 

is it still relevant?

**Comment by orbitwebsites-cloud** [comment]
/attempt #837

**Implementation plan:**
Implement a more comprehensive parsing and evaluation mechanism for permission conditions to ensure thorough coverage and accuracy.

Will submit a PR shortly.

**Comment by orbitwebsites-cloud** [comment]
/attempt #837

**Implementation plan:**
Implement a more comprehensive condition evaluation algorithm to assess all aspects of permission conditions, potentially involving natural language processing or rule-based systems, and update the 'Coverage' command to utilize this new algorithm.

Will submit a PR shortly.

**Comment by hieu-lee** [comment]
/attempt #837

Implementation plan: add focused condition-component coverage to the existing coverage command by walking compiled permission expression trees, reporting uncovered relation/attribute/tuple-to-userset/call/nested-permission leaves per scenario, using scenario context plus shape data to decide whether each component is exercised. I will keep the patch scoped to coverage reporting and add tests for the sample partial-coverage case.

**Comment by Iineman2** [comment]
/attempt #837

Implementation plan:
- Trace the existing coverage command evaluation path and locate where permission conditions are flattened/marked covered.
- Add expression-tree aware coverage so composite permissions such as system.view OR nested groups report partial coverage instead of treating one satisfied branch as full coverage.
- Add focused tests for nested OR/AND/NOT cases using the sample condition from the issue.
- Keep the output/API shape compatible unless the existing tests show a dedicated coverage report model to extend.

**Comment by Iineman2** [comment]
/claim #837

Submitted PR: https://github.com/Permify/permify/pull/2955

Verification run locally:
- go test ./pkg/development/coverage
- go test ./pkg/cmd ./pkg/development/coverage

**Comment by hieu-lee** [comment]
/claim #837

Submitted PR: https://github.com/Permify/permify/pull/2954

Verification run locally:
- go test ./pkg/development/coverage ./pkg/cmd
- go test ./pkg/development/... ./pkg/cmd
- go run ./cmd/permify coverage /Users/hieu.leduc/Desktop/codex-money-maker/artifacts/permify-837/condition-coverage-demo.yaml
- go run ./cmd/permify coverage --coverage-conditions 100 /Users/hieu.leduc/Desktop/codex-money-maker/artifacts/permify-837/condition-coverage-demo.yaml exits with permission condition coverage < 100%

Demo video: https://github.com/hieu-lee/permify/blob/permify-837-demo/demos/permify-837/condition-coverage-demo.mp4
